### ISSUE TITLE
Render and Change events not emitted

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#13]
For RadioButtonGroup/CheckboxGroup the only event that is being emitted is State event. 

We create the experiment using
tests/Testcase_radiobutton.py

Example of an experiment we ran
study_definition_id=1090

The results are being dumped using 
examples/learning_study/dump_results.py

This is the data that we get for the trial 
![image](https://github.com/user-attachments/assets/77c443f3-a70a-46cd-bddb-5f383566369b)

**Comment by madjens** [comment]
With this change we have now lost the entity_type and kind information on the state point_type. 

![image](https://github.com/user-attachments/assets/e057c131-086c-4726-bc89-4fb02e87529d)

Example running tests/Testcase_radiobutton.py 

Version where the data is missing
study_id = 1090 protocol_id = 1088

**Comment by iainbryson** [comment]
@madjens this should be fixed now. Can you verify?

**Comment by madjens** [comment]
yes this works now
