### ISSUE TITLE
Freetext value incorrectly set

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#18]
The freetext component is returning incorrect text value when the user changes the text in the box. See example below. 

Here the value of the instrument is set to the first value that user inputs i.e. 'd'

However the user continued to type additional text and the end result was 'Adler' marked with green. But the instrument returned 'd' (which was the first thing that they entered. )

In addition, the entity_type and kind field are not filled for the Freetext (marked with red)

![image](https://github.com/user-attachments/assets/2bac2abe-2e4c-4148-8f1a-c7769a5725e8)

**Comment by iainbryson** [comment]
Is this fixed, @madjens ? I believe the only existing issue is the multiple render events

**Comment by madjens** [comment]
yes it is fixed
