### ISSUE TITLE
Freetext box has wrong label position

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#19]
The label position of the Freetext instrument is not enforced. i.e. if running tests/Testcase_freetext.py

We vary the Label position field

LabelPosition='top',
LabelPosition='left',
LabelPosition='right',
LabelPosition='bottom',

however as seen on the screenshot, this label is always on top.

![image](https://github.com/user-attachments/assets/33e1370d-c741-49b9-ae6f-9a6e19ae5cbb)

**Comment by iainbryson** [comment]
This should be fixed now.
