### ISSUE TITLE
ColumnWidthPercent not enforced correctly

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#20]
I have tested the new layout setting and the ColumnWidthPercent doesnt seem to be used for the no stimuli case

code to reproduce tests/Testcase_likertscale.py

Example experiment
https://elicit-experiment.com/studies/1130/protocols/1128

![image](https://github.com/user-attachments/assets/1e7da8a1-6d70-4e42-8ada-39ee89388bed)

Setting the column width to either 30 or 80 does not have an affect. More importantly in the case of an audio stimuli, there is a large gap between the instrument and the stimuli, leaving the instrument to the far right. We want to have a a column with the same width for the whole page.

**Comment by iainbryson** [comment]
@madjens a question about what you want the behavior here to be:

The components are always centered right now, and so this means if we set the width at 30% it won't make a large visible difference. Do you want to always right align? e.g.
![image](https://github.com/user-attachments/assets/509c88b4-b827-40d7-9758-176e63608302)

A similar issue arises with the stimulus issue. We can shrink the column size, and this is what you'd see:

![image](https://github.com/user-attachments/assets/45c58a95-4e70-4404-9f2c-759355de19b1)

Is that reasonable? The other option would be to always left-align the stimulus maybe, but it would likely change a lot of things and require tweaking:

![image](https://github.com/user-attachments/assets/e75164f3-c8ae-4865-9fad-1f156cdd03aa)

**Comment by madjens** [comment]
I was thinking something like this where the page is divided in to 2 columns that each have a width (total size 100), which remain the same size regardless whether there is stimuli attached or not so the scales are aligned across the page. I.e. we no longer have the options AlignToStimuli

![image](https://github.com/user-attachments/assets/7f659330-9b52-4836-bb84-619036b00554)

Within each column we want it to look uniform across the page (with or without the stimuli) 

I think the HeaderLabel should be centered above the stimuli, i.e. the last image you show looks bad as the playbutton is all the way to the right compared to the text. But the position of the label compared to the instrument is good i think.

**Comment by madjens** [comment]
So essentially regardless of there is an instrument in the component, the instrument is still the same size.

**Comment by iainbryson** [comment]
I've deployed a change to allow specifying the layout at the component level, so you can set the column widths in all cases: 1 instrument, no stimulus, 1 instrument + 1 stimulus, 1 solo stimulus.


e.g.

```
  Layout:
    Type: column
    ColumnWidthPercent: [ 30, 70 ]
```

The array is the percentage for first the stimulus, then the instrument.
