### ISSUE TITLE
X1AxisLabel, X2AxisLabel not displayed for OneDScale

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#21]
X1AxisLabel, X2AxisLabel is not being displayed on the OneDScale instrument. 

Code to reproduce bug
tests/Testcase_onedscale.py

Screenshot of bug
![image](https://github.com/user-attachments/assets/2bb3852f-77ac-4e81-9366-278f9fd6d260)

**Comment by iainbryson** [comment]
@madjens I don't see where the labels are consumed in the code so I don't see a bug to fix. Where do you want these labels to appear?

**Comment by madjens** [comment]
Something like this

![image](https://github.com/user-attachments/assets/6750a597-7f82-458b-895c-eedf0ff9791c)

**Comment by iainbryson** [comment]
This should be done.

**Comment by iainbryson** [comment]
Fixed (again)

![image](https://github.com/user-attachments/assets/a19eab81-0a30-4dbd-a66f-cce803ed8aef)
