### ISSUE TITLE
RadiobuttonGroup disabled when IsOptional=0

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#25]
When we define a radiobuttongroup and set IsOptional=1, after an option is selected, the scale is grayed out. 

![image](https://github.com/user-attachments/assets/7d39beca-d089-47fc-bba6-067101ec75f2)

We still want the user to be able to change their selection

**Comment by iainbryson** [comment]
Also, related to that, I think the label is wrong: `IsOptional=0` means the question _does_ have to be answered, no?

![image](https://github.com/user-attachments/assets/2c88899d-dda6-4fb7-9359-f05ab083e447)

**Comment by madjens** [comment]
You are absolutely right. I forgot about the AnswerOnce option. I think starting some documentation of all these options would be a good idea. I can start noting all these options down for each instrument, so we dont forget what effect they have.
