### ISSUE TITLE
Radiobuttongroup with feedback only shows feedback when answer is correct

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#26]
Currently the user has to select a correct option for the Radiobuttongroup when the feedback options is enabled.
If the user selects an options that is defined as false, the 'See Answers' button makes the Radiobuttongroup blink orange, as if one hasnt selected any options. 

![image](https://github.com/user-attachments/assets/491a1421-b697-4275-987f-fdc7ac4fdc96)

Code the reproduce the bug
tests/Testcase_radiobutton.py

**Comment by iainbryson** [comment]
I think this is related to `MustAnswerCorrectly=True` in the definition for this component:

https://github.com/elicit-experiment/client-api/blob/3063be65a3cf34a5fde159c42d4e74723fa1421d/tests/Testcase_radiobutton.py#L207

![image](https://github.com/user-attachments/assets/34db62a6-69db-405a-bb2f-152433cb5a6b)

**Comment by madjens** [comment]
Yes you are totally right, forgot about that options. We need to document all these settings >)
