### ISSUE TITLE
FaceLandmarker not saving data when Include are not specified

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/frontend#32]
If we leave these two empty, then no blendshapes or landmarks are saved
IncludeBlendshapes='',
IncludeLandmarks = '',

The same if they are not specified, then no blendshapes or landmarks are saved
#IncludeBlendshapes='',
#IncludeLandmarks = '',

e.g. see tests/Testcase_landmarker.py

**Comment by iainbryson** [comment]
This should be fixed now.
